# Generated by Django 4.2.7 on 2023-11-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_printersmodel_printed_pages_all_oid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printers_in_service',
            options={'ordering': ['print_server', 'location', 'printers', 'serial_number'], 'verbose_name': 'Принтер (учет)', 'verbose_name_plural': '(3) Принтеры (учет)'},
        ),
    ]
