# Generated by Django 4.2.7 on 2023-11-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_alter_printers_in_service_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Printers_in_service',
            new_name='Printers_in_serviceModel',
        ),
        migrations.RenameIndex(
            model_name='printers_in_servicemodel',
            new_name='printers_pr_serial__f412ea_idx',
            old_name='printers_pr_serial__46998d_idx',
        ),
    ]
