# Generated by Django 4.2.7 on 2023-11-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_printers_in_service_commentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='name_on_print_server',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя на Print-server'),
        ),
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='print_server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='printers.print_serversmodel', verbose_name='print-server'),
        ),
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='status_printer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='printers.statusprintersmodel', verbose_name='Статус'),
        ),
    ]
