# Generated by Django 4.2.7 on 2023-11-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_alter_printers_in_servicemodel_name_on_print_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='name_on_print_server',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Имя на Print-server'),
        ),
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='print_server',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='printers.print_serversmodel', verbose_name='print-server'),
        ),
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='printers',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='printers.printersmodel', verbose_name='Модель принтера'),
        ),
    ]
