# Generated by Django 4.2.7 on 2023-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0010_alter_printers_in_servicemodel_name_on_print_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Переведен в архив'),
        ),
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-address'),
        ),
    ]
