# Generated by Django 4.2.7 on 2023-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0011_alter_printers_in_servicemodel_archived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printers_in_servicemodel',
            options={'ordering': ['-status_printer', '-print_server', 'location', 'printers', 'serial_number'], 'verbose_name': 'Принтер (учет)', 'verbose_name_plural': '(3) Принтеры (учет)'},
        ),
        migrations.AddField(
            model_name='printers_in_servicemodel',
            name='service_object',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Объект_обслуживания'),
        ),
    ]
