# Generated by Django 4.2.7 on 2023-11-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0012_alter_printers_in_servicemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_objectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_object_name', models.CharField(max_length=100, unique=True, verbose_name='Объект_обслуживания')),
            ],
            options={
                'verbose_name': 'Объект_обслуживания',
                'verbose_name_plural': '(3) Объекты_обслуживания',
                'ordering': ['service_object_name'],
                'indexes': [models.Index(fields=['service_object_name'], name='printers_se_service_84adeb_idx')],
            },
        ),
        migrations.AlterField(
            model_name='printers_in_servicemodel',
            name='service_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='printers.service_objectmodel', verbose_name='Объект_обслуживания'),
        ),
    ]
