# Generated by Django 4.2.7 on 2023-11-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0013_service_objectmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printed_pagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printed_pages', models.IntegerField(default=0, null=True, verbose_name='Распечатано страниц')),
                ('printers_in_service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printers_in_service_fk', to='printers.printers_in_servicemodel', verbose_name='Принтер (учет)')),
            ],
            options={
                'verbose_name': 'Распечатано страниц',
                'verbose_name_plural': '(4) Распечатано страниц',
                'ordering': ['created'],
                'get_latest_by': 'created',
                'indexes': [models.Index(fields=['created'], name='printers_pr_created_59ebf1_idx')],
            },
        ),
    ]
