# Generated by Django 4.2.7 on 2023-11-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0014_printed_pagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printed_pagesmodel',
            name='printers_in_service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printers_in_service_fk', to='printers.printers_in_servicemodel', verbose_name='Принтер (учет)'),
        ),
    ]
