# Generated by Django 4.2.7 on 2023-11-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0016_alter_service_objectmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printed_pagesmodel',
            name='printers_in_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printers_in_service_fk', to='printers.printers_in_servicemodel', verbose_name='Принтер (учет)'),
        ),
        migrations.AlterField(
            model_name='printers_in_service_commentsmodel',
            name='printers_in_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='printers.printers_in_servicemodel', verbose_name='Принтер (учет)'),
        ),
        migrations.AlterField(
            model_name='printersmodel',
            name='printed_pages_all_oid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printed_pages_all_oid', to='printers.snmp_oidmodel', verbose_name='Распечатано страниц (всего) OID'),
        ),
        migrations.AlterField(
            model_name='printersmodel',
            name='sn_oid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sn_oid', to='printers.snmp_oidmodel', verbose_name='S/N OID'),
        ),
        migrations.AlterField(
            model_name='snmp_oidmodel',
            name='type_OID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_OID', to='printers.type_oidmodel', verbose_name='Type_OID'),
        ),
    ]
