# Generated by Django 4.2.7 on 2023-12-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0018_alter_printers_in_servicemodel_printers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printed_pagesmodel',
            options={'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'Распечатано страниц', 'verbose_name_plural': '(4) Распечатано страниц'},
        ),
    ]
