# Generated by Django 4.2.7 on 2024-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0019_alter_printed_pagesmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printed_pagesmodel',
            options={'get_latest_by': 'created', 'verbose_name': 'Распечатано страниц', 'verbose_name_plural': '(4) Распечатано страниц'},
        ),
        migrations.AlterModelOptions(
            name='printers_in_servicemodel',
            options={'ordering': ['status_printer', 'print_server', 'location', 'printers', 'serial_number'], 'verbose_name': 'Принтер (учет)', 'verbose_name_plural': '(3) Принтеры (учет)'},
        ),
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-address'),
        ),
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='location',
            field=models.CharField(default=0, max_length=100, verbose_name='Локация/Кабинет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='name_on_print_server',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя на Print-server'),
        ),
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='printers_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Модель принтера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='serial_number',
            field=models.CharField(default=0, max_length=50, verbose_name='S/N'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='service_object_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Объект_обслуживания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printed_pagesmodel',
            name='printers_in_service',
            field=models.IntegerField(default=0, verbose_name='id принтера'),
            preserve_default=False,
        ),
    ]
