# Generated by Django 4.2.14 on 2025-07-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0020_alter_printed_pagesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printed_pagesmodel',
            name='error_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ошибки'),
        ),
    ]
